version: "3"

volumes:
  config:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.6.12
    container_name: etcd
    user: root
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    entrypoint: /usr/local/bin/etcd
    command:
      - "--advertise-client-urls=http://0.0.0.0:2379"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--data-dir=/etcd_data"
    ports:
      - "2379:2379/tcp"

  apisix:
    image: "apache/apisix"
    container_name: apisix
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9180:9180/tcp"
      - "9443:9443/tcp"

  dashboard:
    image: "apache/apisix-dashboard:3.0.1-alpine"
    container_name: apisix-dashboard
    restart: always
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9000:9000/tcp"

  prometheus:
    image: prom/prometheus:v3.12.0
    container_name: prometheus
    ports:
      - "9093:9090"
    volumes:
      - ./prometheus:/config
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/config/prometheus.yml"

  grafana:
    image: grafana/grafana:13.0.2
    container_name: grafana
    ports:
      - "3002:3000"
    volumes:
      - "./grafana_conf/provisioning:/etc/grafana/provisioning"
      - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
      - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
    restart: unless-stopped
